server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/GN
    username: postgres
    password: 2343480
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect